[package]
name = "git-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-testing-lib = { git = "https://github.com/Toasterson/git-testing-lib.git", version = "0.1.0" }
